### ISSUE TITLE
Tracker of Issues in Other Crates

### ISSUE THREAD

**Issue by Dylan-DPC-zz** [rust-cli/team#14]
Open issues in other crates that we can target to improve the CLI ecosystem as discussed in [the first meeting](https://github.com/rust-lang-nursery/cli-wg/issues/1)

CLI Args handling: 
- [ ]  [clap 3.0 release](https://github.com/kbknapp/clap-rs/issues/1037)

? in Main:
- [ ] [RFC 1937](https://github.com/rust-lang/rust/issues/43301)

CI for binaries:
- [ ] [trust](https://github.com/japaric/trust/issues)
- [ ] [crate-ci documentation](https://github.com/crate-ci/crate-ci.github.io/issues)

CLI Integration tests:
- [ ] [assert_cli](https://github.com/killercup/assert_cli/issues)
- [ ] [dir_diff](https://github.com/steveklabnik/dir-diff/issues)

Man page / help docs:
- [ ] [clap-rs](https://github.com/kbknapp/clap-rs/issues/552)
